"""P6 ingestion tables: documents, chunks, features, feature_versions, feature_relations,
review_items, audit_events (plans/ingestion.md §4 / §11.1). Embeddings live in Qdrant, not here;
the LangGraph checkpointer creates its own tables at runtime.

Revision ID: af833a3ba944
Revises:
Create Date: 2026-09-26 20:05:40.947531

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "af833a3ba944"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("feature_id", sa.Uuid(), nullable=True),
        sa.Column("graph", sa.String(), nullable=False),
        sa.Column("node", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column(
            "detail", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_feature_id"), "audit_events", ["feature_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_project_id"), "audit_events", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_ts"), "audit_events", ["ts"], unique=False)
    op.create_table(
        "documents",
        sa.Column("doc_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("doc_type", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("blob_path", sa.String(), nullable=True),
        sa.Column("upload_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ingestion_status", sa.String(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "doc_type IN ('upload', 'transcript', 'email', 'ticket', 'sheet', 'chat')",
            name="ck_documents_doc_type",
        ),
        sa.CheckConstraint(
            "ingestion_status IN "
            "('pending', 'parsed', 'extracted', 'consolidated', 'done', 'failed')",
            name="ck_documents_ingestion_status",
        ),
        sa.PrimaryKeyConstraint("doc_id"),
        sa.UniqueConstraint("project_id", "content_hash", name="uq_documents_project_content_hash"),
    )
    op.create_index(op.f("ix_documents_project_id"), "documents", ["project_id"], unique=False)
    op.create_table(
        "features",
        sa.Column("feature_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("lifecycle_state", sa.String(), nullable=False),
        sa.Column("classification", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("readiness", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("override", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle_state IN ('extracted', 'consolidated', 'conflicted', 'classified', "
            "'assessing', 'awaiting_answers', 'answered', 'dev_ready', 'overridden', 'stale', "
            "'in_breakdown', 'needs_review', 'broken_down')",
            name="ck_features_lifecycle_state",
        ),
        sa.PrimaryKeyConstraint("feature_id"),
    )
    op.create_index(
        op.f("ix_features_lifecycle_state"), "features", ["lifecycle_state"], unique=False
    )
    op.create_index(op.f("ix_features_project_id"), "features", ["project_id"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("doc_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("section_path", sa.String(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["doc_id"], ["documents.doc_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("chunk_id"),
        sa.UniqueConstraint("doc_id", "ordinal", name="uq_chunks_doc_ordinal"),
    )
    op.create_index(op.f("ix_chunks_doc_id"), "chunks", ["doc_id"], unique=False)
    op.create_index(op.f("ix_chunks_project_id"), "chunks", ["project_id"], unique=False)
    op.create_table(
        "feature_relations",
        sa.Column("feature_id_a", sa.Uuid(), nullable=False),
        sa.Column("feature_id_b", sa.Uuid(), nullable=False),
        sa.Column("relation_type", sa.String(), nullable=False),
        sa.CheckConstraint(
            "relation_type IN ('depends_on', 'extends', 'conflicts_with')",
            name="ck_feature_relations_relation_type",
        ),
        sa.ForeignKeyConstraint(["feature_id_a"], ["features.feature_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["feature_id_b"], ["features.feature_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("feature_id_a", "feature_id_b", "relation_type"),
    )
    op.create_index(
        op.f("ix_feature_relations_feature_id_b"),
        "feature_relations",
        ["feature_id_b"],
        unique=False,
    )
    op.create_table(
        "feature_versions",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("feature_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "source_refs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("created_from", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["feature_id"], ["features.feature_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("version_id"),
        sa.UniqueConstraint(
            "feature_id", "version_no", name="uq_feature_versions_feature_version_no"
        ),
    )
    op.create_index(
        op.f("ix_feature_versions_feature_id"), "feature_versions", ["feature_id"], unique=False
    )
    # features <-> feature_versions is circular: add the current-version FK once both exist.
    op.create_foreign_key(
        "fk_features_current_version_id",
        "features",
        "feature_versions",
        ["current_version_id"],
        ["version_id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "review_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("feature_id", sa.Uuid(), nullable=True),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_by", sa.String(), nullable=True),
        sa.CheckConstraint("kind IN ('conflict', 'sweep_flag')", name="ck_review_items_kind"),
        sa.CheckConstraint(
            "status IN ('open', 'approved', 'dismissed')", name="ck_review_items_status"
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.doc_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["feature_id"], ["features.feature_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_items_document_id"), "review_items", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_items_feature_id"), "review_items", ["feature_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_items_project_id"), "review_items", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_review_items_status"), "review_items", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_features_current_version_id", "features", type_="foreignkey")
    op.drop_index(op.f("ix_review_items_status"), table_name="review_items")
    op.drop_index(op.f("ix_review_items_project_id"), table_name="review_items")
    op.drop_index(op.f("ix_review_items_feature_id"), table_name="review_items")
    op.drop_index(op.f("ix_review_items_document_id"), table_name="review_items")
    op.drop_table("review_items")
    op.drop_index(op.f("ix_feature_versions_feature_id"), table_name="feature_versions")
    op.drop_table("feature_versions")
    op.drop_index(op.f("ix_feature_relations_feature_id_b"), table_name="feature_relations")
    op.drop_table("feature_relations")
    op.drop_index(op.f("ix_chunks_project_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_doc_id"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_features_project_id"), table_name="features")
    op.drop_index(op.f("ix_features_lifecycle_state"), table_name="features")
    op.drop_table("features")
    op.drop_index(op.f("ix_documents_project_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_audit_events_ts"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_project_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_feature_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
